gofixpoint/fixpoint

src/fixpoint/memory/__init__.py, src/fixpoint/memory/_memgpt.py, tests/memory/test_memgpt.py
Add a simple memory summarization implementation, inspired by MemGPT. The `MemGPTSummaryAgent` keeps track of all historical messages, and whenever the message history exceeds the context window, it summarizes the history and swaps in the summary.
The `MemGPTSummaryAgent` still needs a little work. For example, we should be able to keep some system configuration messages outside of message summary so that they are always present and are not mixed into the summary.
=> Add a simple memory summarization implementation inspired by MemGPT

poetry.lock, pyproject.toml
The new Instructor v1.3.0 version fails:
https://github.com/jxnl/instructor/issues/697
Let's stay on v1.2.x for now.
=> Fix build problem with new Instructor version

src/fixpoint/_utils/completions.py, src/fixpoint/agents/__init__.py, src/fixpoint/agents/mock.py, src/fixpoint/agents/openai.py, src/fixpoint/agents/protocol.py, tests/agents/mock_test.py, tests/agents/openai_test.py, tests/utils/completions_test.py
We have a `BaseAgent` protocol, which is an API that is not constrained to be OpenAI compliant, which is part of the core of the Fixpoint framework.
However, we also want an OpenAI-compliant API, so we have two different classes for interacting with OpenAI:
- `OpenAI` - intended to be a drop-in replacement for the `openai.OpenAI` client.
- `OpenAIAgent` - interacts with the OpenAI API, but conforms to our `BaseAgent` protocol.
When we make a completion from the `OpenAIAgent`, it can interact with memory, and pre and post-completion hooks. The
`agent.chat.completions.create` function used to not have any of these features, but now we have reconciled the two so that the `OpenAI` class uses the `OpenAIAgent` under the hood so we get these extra goodies.
=> Reconcile OpenAI interface and our BaseAgent protocol

src/fixpoint/agents/mock.py, src/fixpoint/agents/openai.py, src/fixpoint/agents/protocol.py, src/fixpoint/analyze/memory.py, src/fixpoint/memory/__init__.py, src/fixpoint/memory/_memgpt.py, src/fixpoint/memory/_memory.py, src/fixpoint/workflow/__init__.py, src/fixpoint/workflow/_workflow.py, src/fixpoint/workflow/protocol.py, tests/agents/mock_test.py, tests/memory/test_memgpt.py, tests/memory/test_memory.py
Create a `fixpoint.workflow` module and then hook up the workflow objects into an agent's `create_completion` method, so that we can mark the completion as belonging to that workflow.
We modified the `fixpoint.memory` so that each memory item is now a `MemoryItem` class instead of a tuple of input messages and output completion. Then we could add the workflow entry to the `MemoryItem`.
=> Hook up workflows into agent

src/fixpoint/agents/mock.py, src/fixpoint/agents/openai.py, src/fixpoint/cache/protocol.py, src/fixpoint/cache/tlru.py, tests/agents/mock_test.py, tests/cache/tlru_test.py
Several changes:
* Plug cache into Agent code (mock + openai)
* Remove `SupportsTLRUCache` and consolidate caching logic into `SupportCacheItem`. `ttl` argument is now passed as an argument into a constructor of a class that inherits `SupportsTLRUCache`
=> Changes to the caching protocols + hook up caching to agents

src/fixpoint/agents/__init__.py, src/fixpoint/agents/_shared.py, src/fixpoint/agents/mock.py, src/fixpoint/agents/openai.py, src/fixpoint/agents/protocol.py, src/fixpoint/cache/__init__.py, src/fixpoint/cache/_shared.py, src/fixpoint/cache/disktlru.py, src/fixpoint/prompting/classification.py, src/fixpoint_extras/services/formagent/setup.py, src/fixpoint_extras/services/formagent/steps.py
Allow us to control when an agent caches. We add a `CacheMode` parameter to the agent implementation classes, and also let the caller of `agent.create_completion` manually specify a cache mode override.
Also add some debug logging throughout the `fixpoint.cache` module. There is a `fixpoint.cache.logger` object so that you can control the log level for the caching, specifically.
=> Allow control over when agent caches

src/fixpoint/cache/_shared.py, src/fixpoint/cache/disktlru.py, src/fixpoint/cache/tlru.py, tests/agents/mock_test.py, tests/cache/disktlru_test.py, tests/cache/tlru_test.py
The Python `hash` function is not stable across new instances of the Python VM. Furthermore, with some caches it would be useful to preserve the semantic meaning of the cache keys instead of randomizing them. For example, if we want to later add support to iterate over all cache key entries or do semantic caching.
To solve both these problems, we stop hashing with the builtin `hash` function to pseudo-random integers, and make these two changes:
1. The `DiskTLRUCache` requires you pass in a `serialize_key_fn` that converts the key to a string
2. The `DiskTLRUCache` doesn't do any special stuff, instead just using the implementations default pickling for serialization.
=> Fix caching key stability bug

src/fixpoint/agents/_shared.py, src/fixpoint/agents/mock.py, src/fixpoint/agents/openai.py, src/fixpoint/agents/protocol.py, src/fixpoint/cache/__init__.py, src/fixpoint/cache/disktlru.py, src/fixpoint/cache/protocol.py, src/fixpoint/cache/tlru.py, src/fixpoint/completions/chat_completion.py, src/fixpoint_extras/services/formagent/setup.py, src/fixpoint_extras/services/formagent/workflowcontext.py, tests/agents/mock_test.py, tests/agents/openai_test.py, tests/cache/disktlru_test.py, tests/completions/completions_test.py, tests/test_utils.py, tests/utils/completions_test.py
When we try to cache a ChatCompletion to disk, if it has an inner "structured output" Pydantic model, then the `DiskCache` throws an error when trying to pickle the object. It's possible this error is just related to slightly different import paths on cache save versus load, but regardless, saving pickled objects is not a good strategy.
So we add support for serializing a ChatCompletion to disk as JSON, and loading it back in as JSON. When we load it back in as JSON, we don't know what `Pydantic` class to use for the structured output, so we extended the caching classes to accept a Pydantic class when calling `get`. This was added to a new protocol, `SupportsChatCompletionCache`.
Most of the rest of this commit is just fixing all of the plumbing for caching to use the new …
=> Allow caching of Pydantic models inside ChatCompletions

src/fixpoint/_utils/completions.py, src/fixpoint/agents/_shared.py, src/fixpoint/agents/mock.py, src/fixpoint/agents/openai.py, src/fixpoint/agents/protocol.py, src/fixpoint/cache/disktlru.py, src/fixpoint/cache/protocol.py, src/fixpoint/cache/tlru.py, src/fixpoint/completions/chat_completion.py, src/fixpoint/memory/_memgpt.py, src/fixpoint/memory/_memory.py, src/fixpoint/prompting/classification.py, src/fixpoint_extras/services/formagent/tasks/invoice.py, tests/agents/mock_test.py, tests/memory/test_memgpt.py
Change the `ChatCompletion` class definition so that it accepts a generic type that can be any subclass of `pydantic.BaseModel`. This is the type of the structured data that the `ChatCompletion` can optionally hold.
Then I had to wire up the generics across the codebase when using chat completions. It would be nice if we could make the generic type optional by giving it a default type of `BaseModel`, but we'll need to wait for PEP-696 for that.[1]
Initially, whenever I called `create_completion` without specifying a `response_model` argument, we had to annotate the return type with `ChatCompletion[BaseModel]`. This was annoying. PEP-696 would have fixed this, but an alternative fix we can do right now is to overload the `BaseAgent.create_completion` definition so that we can better infer …
=> ChatCompletion has generic type for structured output

.pylintrc, src/fixpoint_extras/services/formagent/controllers/__init__.py, src/fixpoint_extras/services/formagent/controllers/infogather.py, src/fixpoint_extras/services/formagent/tasks/__init__.py, src/fixpoint_extras/services/formagent/tasks/invoice.py
Add an InfoGatherer controller that can control an agent whose job it is to gather answers to a set of form fields.
There's a new concept here, of a "controller". A controller can be thought of a controller (duh) or a manager of other AI agents and the process for how they work together to accomplish something. It's a higher level way to compose and coordiante agents.
Later there could be some overlap of responsibility between "agents" and "controllers", but I think of the difference like this:
Agents are backed by some AI, and they can take multiple steps, but generally you just ask the agent to accomplish something and it does it.
Controllers can layer on top of a single agent, or can coordinate multiple agents, and expose interfaces designed to be controlled by our software systems or …
=> Add an InfoGatherer controller

src/fixpoint/cache/protocol.py, src/fixpoint/cache/tlru.py
It's done so that all elements of the cache including it's key can be stored in the database
=> Expand  the TLRUCacheItem definition

src/fixpoint/completions/chat_completion.py, src/fixpoint_extras/services/formagent/controllers/infogather.py
We were getting this error when initing new `ChatCompletion` instances:
> GenericBeforeBaseModelWarning: Classes should inherit from `BaseModel`
> before generic classes (e.g. `typing.Generic[T]`) for pydantic
> generics to work properly.
I swapped the order of the parent classes that `ChatCompletion` inherits
from, and this caused other errors. I fixed this by making the
`ChatCompletion.Fixp` class also inherit `pydantic.BaseModel`.
=> Fix warnings instantiating ChatCompletion instance

.gitignore, docs/src/lib/utils.ts, src/fixpoint/agents/callbacks/__init__.py, src/fixpoint/agents/protocol.py, src/fixpoint/analyze/memory.py, src/fixpoint/memory/_memory.py, src/fixpoint_extras/services/formagent/setup.py, tests/agents/mock_test.py, tests/memory/test_memgpt.py, tests/memory/test_memory.py
Move agent pre- and post-callbacks to separate module.
Fix weird gitignore issue ignoring "lib/" folders.
Rename the `Memory.memory` function to `memories` because it makes it clearer that we are getting the list of all memories.
=> A few dev UX improvements and code re-orgs

src/fixpoint/cache/tlru.py, tests/agents/mock_test.py, tests/cache/tlru_test.py
Make a few little improvements to the TLRUCache and the ChatCompletionTLRUCache:
1. rename `ttl` to `ttl_s` to indicate units (seconds)
2. the `ChatCompletionTLRUCache.__init__` does not require a `serialize_key_fn` because we know we should use `json.dumps`
=> Little improvements to TLRUCache

bin/test, db/migrations/20240519224547_initial-tables.sql, src/fixpoint/cache/tlru.py, src/fixpoint/storage/protocol.py, src/fixpoint/storage/supabase.py, tests/cache/tlru_test.py, tests/memory/test_memory.py, tests/storage/supabase_test.py, tests/supabase_test_utils.py, tests/workflows/imperative/test_forms.py
Fix TLRUCache and Supabase test failure
The tests for the TLRUCache with Supabase storage failed because the
TLRUCacheItem did not implement `SupportsSerialization`. Fix this.
Supabase and database testing
Make some improvements to how our tests integrate with Supabase.
`bin/test` parses out the Supabase environment variables when running
test.
Fix the `db/migrations` files so that they run.
Rename the Pytest fixture `test_inputs` to `supabase_setup_url_and_key`
so that it is easier to understand what the fixture is doing.
Conditionally run all Supabase tests if the necessary environment
variables are defined.
=> Fix Supabase tests

src/fixpoint/storage/supabase.py, src/fixpoint_extras/services/formagent/controllers/infogather.py, src/fixpoint_extras/workflows/imperative/form.py, src/fixpoint_extras/workflows/imperative/workflow.py, tests/workflows/imperative/test_forms.py
Make the Workflow Form serialization/deserialization logic use the underlying JSON schema. This is more durable for long-term storage than relying on import paths of Pydantic models, and theoretically it lets us support non-Python languages in the future.
As part of this, we limit the types of forms that users can create so that it is easy to do form deserialization. We force the form to:
1. only support simple non-nested fields: bool, str, int, float
2. each field must be optional, since the form starts empty and we fill it in
We also update the logic for how a form is updated. When you call `form.update`, it only updates the fields you specify, leaving the other ones as is.
Finally, make a little change in how Supabase storage does form serialization and deserialization. We used to …
=> Improve workflow form serialization and updates

src/fixpoint/agents/_shared.py, src/fixpoint/agents/mock.py, src/fixpoint/agents/oai/openai.py, src/fixpoint/agents/openai.py, src/fixpoint/agents/protocol.py, src/fixpoint/cache/__init__.py, src/fixpoint/cache/_shared.py, src/fixpoint/cache/chattlru.py, src/fixpoint/cache/disktlru.py, src/fixpoint/cache/protocol.py, src/fixpoint/storage/supabase.py, tests/agents/mock_test.py, tests/cache/disktlru_test.py, tests/cache/test_chat_completion_cache.py, tests/cache/tlru_test.py, tests/memory/test_memory.py
When we make a chat completion request, we used to only do caching based on the "messages" parameter. However, there are a bunch of other model parameters that affect the response, such as the model used or the temperature.
Now, we cache based on more completion request parameters. We don't cover all arguments to OpenAI yet, but more of them.
Along the way, I tried to make serialization and deserialization of work for pairs of:
- CreateChatCompletionRequest
- ChatCompletion
The problem here is that both of these types contain a Pydantic model class and instance, respectively. This type does not serialize or deserialize cleanly. You must know what class to use when deserializing.
We kind of kludge this into working for now. It was difficult for me to use the `TLRUCache`. I tried to get …
=> Make chat completion caching support more chat completion parameters

src/fixpoint_extras/workflows/imperative/workflow_context.py
Change the `WorkflowContext` so that it uses the imperative `WorkflowRun` instead of `SupportsWorkflowRun`.
=> WorkflowContext uses imperative WorkflowRun

examples/structured_workflow.py, src/fixpoint_extras/workflows/imperative/workflow.py, src/fixpoint_extras/workflows/structured/_task.py, tests/extras/workflows/structured/test_task.py, tests/workflows/imperative/test_workflow.py
Fix a few bugs in the structured workflow example so that it runs. Also, use `TaskGroup` for structured concurrency to wait on multiple coroutines. Structured concurrency is a more readable pattern for knowing when all concurrent calls are finished.
Make a few updates to how we represent the workflow node-state path-like ID string. If we are in the main task or step (aka no task or step specified), then we omit that part from the path ID.
When you store a document or form, by default we store it at the workflow's current node.
=> Fix a few bugs in structured workflow example

src/fixpoint_extras/workflows/structured/_workflow.py
We allow users to specify the context in two places:
1. on the workflow class decorated by `@structured.workflow(...)`
2. on the call to `structured.run_workflow(...)`
=> WorkflowContext factory can be defined during `run_workflow`

examples/structured_workflow.py, src/fixpoint/agents/_memgpt.py, src/fixpoint/agents/mock.py, src/fixpoint/agents/openai.py, src/fixpoint/agents/protocol.py, src/fixpoint/memory/__init__.py, src/fixpoint/memory/_no_op_memory.py, src/fixpoint_extras/services/formagent/setup.py, src/fixpoint_extras/workflows/imperative/workflow_context.py, src/fixpoint_extras/workflows/structured/_workflow.py, tests/agents/test_memgpt.py, tests/extras/workflows/structured/test_step.py, tests/extras/workflows/structured/test_task.py
Rework some setup code for workflows and agents. Changes:
**Agent and memory changes**
Agents now have a `memory` field, which is how you can refer to an agent's memory. Before, you would pass in a memory container but there was no way to access the memory container.
Memory is required on all agents. If you don't supply a memory container, we'll use a no-op memory container that doesn't actually store memories. This makes it easier for the rest of the code to assume that we are storing memories.
I had to move the `_memgpt.py` file so that we no longer had a circular import, which was causing a Pylint error.
**Workflow changes**
The `WorkflowContext` is no longer a dataclass, so we have control over its initialization.
`WorkflowContext` no longer accepts a memory field. Instead, the agents …
=> Rework setup code for workflows and agents

db/migrations/20240624012918_mem-cache-docs-and-forms.sql, examples/structured_workflow.py, src/fixpoint/agents/__init__.py, src/fixpoint/agents/_shared.py, src/fixpoint/agents/mock.py, src/fixpoint/agents/oai/openai.py, src/fixpoint/agents/openai.py, src/fixpoint/agents/protocol.py, src/fixpoint/analyze/memory.py, src/fixpoint/cache/__init__.py, src/fixpoint/memory/_memory.py, src/fixpoint/memory/_no_op_memory.py, src/fixpoint/storage/supabase.py, src/fixpoint_extras/services/formagent/setup.py, src/fixpoint_extras/workflows/imperative/_workflow_agent.py, src/fixpoint_extras/workflows/imperative/config.py, src/fixpoint_extras/workflows/imperative/workflow.py, src/fixpoint_extras/workflows/imperative/workflow_context.py, src/fixpoint_extras/workflows/structured/_workflow.py, tests/agents/oai/openai_test.py, tests/cache/test_chat_completion_cache.py, tests/cache/tlru_test.py, tests/extras/workflows/imperative/test_documents.py, tests/extras/workflows/imperative/test_forms.py, tests/extras/workflows/structured/test_step.py, tests/extras/workflows/structured/test_task.py, tests/memory/test_memory.py
Set up factories for configuring all necessary storage for workflows. This includes:
- form storage
- document storage
- agent memory
- agent cache
Also, create a Postgres migration file that configures the appropriate tables. I took the example tables from within the tests, but I made some changes to them. Generally, I made some columns non-nullable, added workflow info to a few tables, and made the memory table support multiple agents. I also updated tests so that the adhoc postgres table creations use the new table formats.
As part of making memory work for multiple agents, we need each agent to have a ID.
Originally, you could specify a ID when creating an agent, and if you don't it will be given a random ID. When you created a structured workflow, you pass in a dictionary of agent …
=> Set up factories for workflow storage

examples/structured_workflow.py, src/fixpoint_extras/workflows/imperative/workflow.py, src/fixpoint_extras/workflows/structured/_workflow.py, src/fixpoint_extras/workflows/structured/_workflow_run_handle.py, tests/extras/workflows/structured/test_workflow.py
Extend the `WorkflowRunHandle` with methods to check the status of the workflow (open/closed) and to get the inner `WorkflowRun` object via `WorkflowRunHandle.finalized_workflow_run(...)`.
`finalized_workflow_run` will only return a `WorkflowRun` if we finished awaiting the coroutine result of the workflow.
Also, squeeze in a little more code into the `examples/structured_workflow.py` file that shows how we can save/load the chat completion results to a dataframe.
=> [structured] Extend WorkflowRunHandle functionality

src/fixpoint/workflows/structured/_callcache/_converter.py, tests/workflows/structured/_callcache/test_converter.py
Add a `_converter.py` file to the `structured._callcache` module. The `_converter` module is for deserializing text into typed values. Without this, we would just deserialize JSON to simple dicts or lists or something, but with this we can deserialize based on type-hints, thus supporting Pydantic or dataclass deserialization.
This was taken from Temporal, which we attribute at the top of the source file.
=> Add callcache converter file for deserialization to types

src/fixpoint/_constants.py, src/fixpoint/workflows/imperative/config.py, src/fixpoint/workflows/structured/_callcache/__init__.py, src/fixpoint/workflows/structured/_callcache/_disk.py, src/fixpoint/workflows/structured/_callcache/_in_mem.py, src/fixpoint/workflows/structured/_callcache/_shared.py, src/fixpoint/workflows/structured/_run_config.py, tests/workflows/structured/_callcache/assertions.py, tests/workflows/structured/_callcache/test_disk.py, tests/workflows/structured/_callcache/test_in_mem.py
Add a structured workflows call-cache for tasks and steps that caches on-disk.
The on-disk callcache to be able to directly accept cache objects so that we can share the same cache for both tasks and steps.
Hook up the on-disk call-cache in the `RunConfig` settings so we can easily configure on-disk caching for structured workflows.
=> Add on-disk caching for structured workflows

examples/simple_memory_and_structure.py, src/fixpoint/memory/__init__.py, src/fixpoint/memory/_mem_storage.py, src/fixpoint/memory/_memory.py, src/fixpoint/memory/_no_op_memory.py, src/fixpoint/memory/protocol.py, src/fixpoint/workflows/imperative/config.py, tests/agents/mock_test.py, tests/experimental/agents/test_memgpt.py, tests/memory/test_memory.py
Prepare the code for on-disk memory storage. We made it so we have a `_mem_storage` module with a `MemoryStorage` protocol instead of using the generic `SupportsStorage` protocol.
We migrated Supabase storage over to use `MemoryStorage`, and have unimplemented stubs for on-disk memory storage.
=> Skeleton code for on-disk memory support

src/fixpoint/workflows/imperative/_doc_storage.py, src/fixpoint/workflows/imperative/_form_storage.py, src/fixpoint/workflows/imperative/config.py, src/fixpoint/workflows/imperative/workflow.py
Add a protocol for doc and form storage in workflows. We used to just use the generic `SupportsStorage` protocol for `Document` and `Form` classes, but that started to become complicated when I was trying to write the SQLite on-disk implementations.
So we go to a resource-based approach, where we have a protocol specified for how to interact specifically with forms and docs.
I added a Supabase compatible implementation of this protocol, which mostly just pipes things through to the old `SupabaseStorage` class.
=> Add protocol for doc and form storage in workflows

src/fixpoint/workflows/imperative/_wrapped_workflow_agents.py, src/fixpoint/workflows/imperative/workflow_context.py, src/fixpoint/workflows/structured/_context.py, tests/workflows/imperative/test_workflow_context.py
Fix the structured `WorkflowContext.clone` method by overriding the child class's `clone` method. If we didn't override, there are problems because structured and imperative `WorkflowContext.__init__` methods have different parameters.
=> [structured] Fix WorkflowContext clone

.pylintrc, examples/fastapi_chat_workflows/server.py, src/fixpoint/workflows/__init__.py, src/fixpoint/workflows/constants.py, src/fixpoint/workflows/imperative/shared.py, src/fixpoint/workflows/imperative/workflow.py, src/fixpoint/workflows/imperative/workflow_context.py, src/fixpoint/workflows/node_state.py, src/fixpoint/workflows/structured/_context.py, src/fixpoint/workflows/structured/_step.py, src/fixpoint/workflows/structured/_task.py, tests/workflows/imperative/test_workflow.py, tests/workflows/structured/test_step.py, tests/workflows/structured/test_task.py, tests/workflows/test_node_state.py
When you call a task or a step in a structured workflow, clone the context and then appropriately update the node state when the task or step is spawned, and then when it either succeeds or fails.
=> [structured] Calling tasks and steps updates context

src/fixpoint/workflows/imperative/workflow_context.py
When you had a `WorkflowContext` and called `wfctx.logger.info(...)` it would not show up. Fiddle with the logger configuration so that `.info` calls work by default.
=> Make workflow context logger `logger.info` work

db/migrations/20240624012918_mem-cache-docs-and-forms.sql, src/fixpoint/_storage/definitions.py, src/fixpoint/workflows/imperative/_doc_storage.py, tests/workflows/imperative/test_documents.py, tests/workflows/imperative/test_workflow.py
For the workflow documents table, we had inconsistent column definitions across these declarations:
1. our migration files in `db/migrations`
2. SQLite instations in `.../imperative/_doc_storage.py`
3. Supabase table creations in `tests/...`
Create a new `src/fixpoint/_storage/definitions.py` file to colocate the "documents" table definition.
Unforunately, we cannot use this Python module in our `db/migrations` files because they are SQL files, but we can use it elsewhere.
=> Fix inconsistencies with "documents" table

db/migrations/20240624012918_mem-cache-docs-and-forms.sql, src/fixpoint/_storage/definitions.py, src/fixpoint/workflows/imperative/_doc_storage.py, src/fixpoint/workflows/imperative/document.py, src/fixpoint/workflows/imperative/workflow.py, tests/workflows/imperative/test_doc_storage.py
Change the API and storage layers for documents so that you can store a document rooted either:
1. on a workflow and a workflow run (the only way previously supported)
2. on a workflow, but outside of any workflow run
3. outside of any workflows
We had to change the storage layers to use composite primary keys for documents. Of note, you cannot have any column of a primary key be nullable in Postgres, so if a document's `workflow_id` or `workflow_run_id` column is NULL, we actually change it to the special string `__null__`.
Fixes Linear issue: https://linear.app/fixpoint/issue/PRO-60/convert-primary-keys-for-docs-and-forms-to-allow-duplicate-ids-in
=> Documents can be stored outside workflow runs or workflows
